### PR TITLE
fix: prevent own_capabilities and hidden set to undefined

### PR DESCRIPTION
**Pull request by yetieaterxb1**
prevent own_capabilities and hidden from being set to undefined after a channel.updated event is fired

link to issue: https://github.com/GetStream/stream-chat-react/issues/1310

### CODE REVIEW

**Review by AnatolyRugalev — APPROVED** [review]

**Comment by mahboubii** [comment]
Could this cause sync issues? Maybe better to keep old data if new channel data is missing it

**Comment by petyosi** [comment]
> Could this cause sync issues? Maybe better to keep old data if new channel data is missing it

@amin How can that happen?

**Comment by BrianLi101** [comment]
Thanks for the fix!

Quick followup, what happens if the `own_capabilities` ends up changing after someone already joined a Channel? For example, they're promoted to a `moderator` and the channel was already watched. This PR technically uses the existing `own_capabilities` on the channel and wouldn't end up updating them off of the new ones from the event.

**Comment by mahboubii** [comment]
> > Could this cause sync issues? Maybe better to keep old data if new channel data is missing it
> 
> @amin How can that happen?

@petyosi Talked with the team and looks like this is not the case now since this event only fired for specific cases. [changed](https://github.com/GetStream/stream-chat-js/pull/849/commits/3f4f8ac21240c453fc73c848a86582db8c74aa51) it a bit to avoid potential future issues

**Comment by mahboubii** [comment]
> Thanks for the fix!
> 
> Quick followup, what happens if the `own_capabilities` ends up changing after someone already joined a Channel? For example, they're promoted to a `moderator` and the channel was already watched. This PR technically uses the existing `own_capabilities` on the channel and wouldn't end up updating them off of the new ones from the event.
> 
> Even with the above possible concerns, it would be great if this could be deployed as soon as possible! We would prefer to use it as a fully supported patch-fix

@BrianLi101 thanks for bringing this up. It is not the case as of now for this event, `own_capabilities` are updated in a different event.

**Comment by BrianLi101** [comment]
@mahboubii Thanks for clarifying! Do you know what the timeline for merging this looks like?

**Review by petyosi — APPROVED** [review]

**Comment by mahboubii** [comment]
> @mahboubii Thanks for clarifying! Do you know what the timeline for merging this looks like?

@BrianLi101 thanks for waiting, fix is released in [v5.1.1](https://github.com/GetStream/stream-chat-js/releases/tag/v5.1.1)

**Comment by BrianLi101** [comment]
@mahboubii Thank you!

**Pull request merged**
