### PR TITLE
chore: update package repo link

### PR DESCRIPTION
**Pull request by theo4u**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

I opened the npm package here: https://www.npmjs.com/package/stream-chat and was unable to locate where the repository was hosted. So this is to add the repository link to the package info panel.

### CODE REVIEW

**Comment by tbarbugli** [comment]
@theo4u thank you the fix, could you follow the link for CLA and after check the box in the PR?

**Comment by theo4u** [comment]
The link is broken: 

image

**Comment by theo4u** [comment]
@tbarbugli ^^

**Comment by tbarbugli** [comment]
@theo4u can you try again the link?

**Comment by theo4u** [comment]
cool, filled and submitted 

cc @tbarbugli

**Pull request merged**
