### PR TITLE
feat: add id_around support for replies

### PR DESCRIPTION
**Pull request by SiddhantAgarwal**
## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] Code changes are tested

## Changelog

-

### CODE REVIEW

**Review by AnatolyRugalev — APPROVED** [review]

**Comment by AnatolyRugalev** [comment]
@peterdeme can you please clarify why linter is not happy? Is PR title a problem or actual commits in PR? If it's the latter, we should change the process since we squash-merge and actual PR commits don't matter. If it's the former, we need to adjust error message in CI

Thank you

**Comment by peterdeme** [comment]
@AnatolyRugalev it was the pr title, I fixed it.

Thi was the error message:
```
$ commitlint
[9](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:9)
⧗   input: Add id_around support for replies.
[10](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:10)
✖   subject may not be empty [subject-empty]
[11](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:11)
✖   type may not be empty [type-empty]
[12](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:12)

[13](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:13)
✖   found 2 problems, 0 warnings
[14](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:14)
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
[15](https://github.com/GetStream/stream-chat-js/runs/5274914276?check_suite_focus=true#step:4:15)
```

How would you like to improve it?

**Comment by AnatolyRugalev** [comment]
@peterdeme job name got me confused:
image

**Review by ferhatelmas — APPROVED** [review]

**Comment by ferhatelmas** [comment]
@vishalnarkhede it seems generics have an issue

**Pull request merged**
