### PR TITLE
fix: fire health.check event after successful connection when using long poll transport

### PR DESCRIPTION
**Pull request by thesyncim**

### CODE REVIEW

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
there are breaking changes on master though, release might be troublesome

**Comment by vishalnarkhede** [comment]
> there are breaking changes on master though, release might be troublesome

@ferhatelmas which one is the breaking change?

**Comment by ferhatelmas** [comment]
node v10 drop

**Pull request merged**
